---
- name: Install vbox
  pacman: name=virtualbox

- name: Add user group
  shell: gpasswd -a {{ user.name }} {{ item }}
  with_items:
    - disk
    - vboxusers

- name: Install virtualbox-host-modules
  pacman: name={{ virtualbox.host }}

- name: Install virtualbox-ext-oracle
  shell: yay -S --needed --noconfirm virtualbox-ext-oracle
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - yay

- name: modprobe vboxdrv
  shell: modprobe vboxdrv
  become: yes
  become_user: "{{ user.name }}"
