---
- name: Edit GRUB_TIMEOUT
  lineinfile:
    dest: /etc/default/grub
    regexp: '^[ 	]*GRUB_TIMEOUT[ 	]*=[ 	]*[0-9]+$'
    insertafter: EOF
    line: 'GRUB_TIMEOUT=1'
  become: yes
  notify: Update config
