---
- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ user.name }}/.dotfiles update=yes
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: submodule
  shell: cd /home/{{ user.name }}/.dotfiles && git submodule init && git submodule update
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  shell: cd /home/{{ user.name }}/.dotfiles && ./rcin deploy
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
