---
- name: HandleLidSwitch in /etc/systemd/logind.conf
  lineinfile:
    dest: /etc/systemd/logind.conf
    state: present
    backrefs: yes
    regexp: '^\s*#\s*HandleLidSwitch\s*=.*'
    line: 'HandleLidSwitch = ignore'

- name: HandleLidSwitchDocked in /etc/systemd/logind.conf
  lineinfile:
    dest: /etc/systemd/logind.conf
    state: present
    backrefs: yes
    regexp: '^\s*#\s*HandleLidSwitchDocked\s*=.*'
    line: 'HandleLidSwitchDocked = ignore'
