- name: unused files
  script: move.sh "{{ item }}"
  register: move
  changed_when: '"unchanged" not in move.stdout'
  become: yes
  with_items:
    - /usr/share/vim/vimfiles/plugin/fzf.vim
    - /usr/share/vim/vimfiles/ftdetect/conkyrc.vim
    - /usr/share/vim/vimfiles/ftdetect/meson.vim
    - /usr/share/vim/vimfiles/ftdetect/nginx.vim
    - /usr/share/nvim/runtime/plugin/netrwPlugin.vim
    - /usr/share/nvim/runtime/plugin/tohtml.vim
    - /usr/share/nvim/runtime/plugin/spellfile.vim
    - /usr/share/nvim/runtime/plugin/tutor.vim
    - /usr/share/nvim/runtime/plugin/zipPlugin.vim
    - /usr/share/nvim/runtime/plugin/tarPlugin.vim
    - /usr/share/nvim/runtime/plugin/gzip.vim

- name: unused filetypes
  script: filetype.py "{{ target }}" "{{ bak }}" "{{ body }}"
  register: ft
  changed_when: '"unchanged" not in ft.stdout'
  become: yes
  vars:
    target: /usr/share/nvim/runtime/filetype.vim
    bak: /usr/share/nvim/runtime/_filetype.vim
    items:
      - "*.inp"
      - "*.8th"
      - "*.aap"
      - "*.abap"
      - "*.abl"
      - "*.aml"
      - "apt.conf"
      - "*.asa"
      - "*.asp"
      - "*.mar"
      - "*.atl,*.as"
      - "*.au3"
      - "*.ahk"
      - "*.ave"
      - "*.mch,*.ref,*.imp"
      - "*.iba,*.ibi"
      - "*.btm"
      - "*.beancount"
      - "*.bib"
      - "*.bst"
      - "*.bl"
      - "*/etc/blkid.tab,*/etc/blkid.tab.old"
      - "*.bzl,*.bazel,WORKSPACE"
      - "calendar"
      - "*/etc/cdrdao.conf,*/etc/defaults/cdrdao,*/etc/default/cdrdao,.cdrdao"
      - "cfengine.conf"
      - "*.recipe"
      - "*.crm"
      - "*.cyn"
      - "*..ch"
      - "*.dcl,*.icl"
      - "*.ent"
      - "*.eni"
      - "*.cfm,*.cfi,*.cfc"
      - "*.dcd"
      - "*enlightenment/*.cfg"
      - "*Eterm/*.cfg"
      - "*.rul"
      - "jbuild,dune,dune-project,dune-workspace"
      - "*.lid"
      - "*.intr"
      - "*.dylan"
      - "*.ecd"
      - "*.e,*.E"
      - "elinks.conf"
      - "*esmtprc"
      - "*.strl"
      - "*.fan,*.fwt"
      - "*.factor"
      - "*.fnl"
      - "*.fex,*.focexec"
      - "*.mas,*.master"
      - "*.frt"
      - "*.ged,lltxxxxx.txt"
      - "gkrellmrc,gkrellmrc_?"
      - "*.gretl"
      - "*.hsm"
      - "*.hws"
      - "*.ijs"
      - "*.jal,*.JAL"
      - "*.jpl,*.jpr"
      - "*.clp"
      - "*.jov,*.j73,*.jovial"
      - "*.ks"
      - "*/LiteStep/*/*.rc"
      - "*.lgt"
      - "*.lot,*.lotos"
      - "*.lou,*.lout"
      - "*.mgp"
      - "*.mgl"
      - "*.mod"
      - "*.m2,*.DEF,*.MOD,*.mi"
      - "*.[mi][3g]"
      - "*.moo"
      - "*.s19,*.s28,*.s37,*.mot,*.srec"
      - "mrxvtrc,.mrxvtrc"
      - "*.NS[ACGLMNPS]"
      - "*.ncf"
      - "*.nqc"
      - "*.nsi,*.nsh"
      - "*.xom,*.xin"
      - "*.or"
      - "*.[Oo][Pp][Ll]"
      - "*.dpr,*.lpr"
      - "*.pike,*.pmod"
      - "*.g"
      - "*.it,*.ih"
      - "*.arr"
      - "*.pyx,*.pxd"
      - "*.rad,*.mat"
      - ".ratpoisonrc,ratpoisonrc"
      - "*\\,v"
      - ".reminders,*.remind,*.rem"
      - "*.rpl"
      - "*.rsc"
      - "*.sl"
      - "*.sci,*.sce"
      - "*.svelte"
      - "*.sim"
      - "*.smt,*.smith"
      - "*.sno,*.spt"
      - "*.rq,*.sparql"
      - "*.speedup,*.spdata,*.spd"
      - "*.ice"
      - "*.sp,*.spice"
      - "*.spy,*.spi"
      - "*.nut"
      - "*.hlp,*.ihlp,*.smcl"
      - "*.cm"
      - "*.sdc"
      - "*.tak"
      - "*.tli"
      - ".tidyrc,tidyrc,tidy.conf"
      - "*.tf,.tfrc,tfrc"
      - "trustees.conf"
      - "*.tssgm"
      - "*.tssop"
      - "*.tsscl"
      - "*.tutor"
      - "*.vr,*.vri,*.vrh"
      - "*.sba"
      - "vgrindefs"
      - "*.wsml"
      - "wvdial.conf,.wvdialrc"
      - ".cvsrc"
      - "*.web"
      - "*.zu"
      - "*.zut"
      - "*.dtml,*.pt,*.cpt"
      - "*.z8a"
    body: "{{ items | join('\n') }}"
