- name: running_user
  shell: id -un
  register: running_user
  changed_when: False
  failed_when: not(running_user.stdout == user.name)

- name: pacman zsh
  pacman: name=zsh state=present

- stat: path=/usr/bin/zsh
  register: zsh

- name: default shell
  user:
    name: "{{ user.name }}"
    shell: /usr/bin/zsh
  become: yes
  when: zsh.stat.xusr

- name: pacman xdg-user-dirs
  pacman: name=xdg-user-dirs state=present

- name: Create dirs
  file:
    path: /home/{{ user.name }}/{{ item }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0755
  with_items:
    - workspace
    - bin
    - chest/own
    - chest/others
    - .config
    - .ssh
    - storage/music
    - storage/pictures
    - storage/videos
    - storage/public
    - storage/desktop
    - storage/templates
    - storage/wallpapers

- name: Copy user-dirs.dirs
  copy:
    src: user-dirs.dirs
    dest: /home/{{ user.name }}/.config/user-dirs.dirs
  notify: Update user-dirs

- name: Copy user-dirs.locale
  copy:
    src: user-dirs.locale
    dest: /home/{{ user.name }}/.config/user-dirs.locale
  notify: Update user-dirs
