---
- name: Check for TRIM support
  shell: nvme id-ctrl /dev/nvme0 -H
  become: yes
  register: info
  changed_when: False

- name: weekly filesystem TRIM timer
  systemd: name=fstrim.timer enabled=yes state=started daemon_reload=yes
  when: '"Data Set Management Supported" in info.stdout'
  become: yes
