---
- name: Check for TRIM support
  shell: hdparm -I /dev/sda
  become: yes
  register: hdparm
  changed_when: False

- name: weekly filesystem TRIM timer
  systemd: name=fstrim.timer enabled=yes state=started daemon_reload=yes
  when: '"TRIM" in hdparm.stdout'
  become: yes
