---
- name: pip
  shell: pip install --user "{{ item }}"
  with_items: "{{ pm.pip }}"
  become: yes
  become_user: "{{ user.name }}"

- name: pip2
  shell: pip2 install --user "{{ item }}"
  with_items: "{{ pm.pip2 }}"
  become: yes
  become_user: "{{ user.name }}"

- name: gem
  shell: gem install "{{ item }}"
  with_items: "{{ pm.gem }}"
  become: yes
  become_user: "{{ user.name }}"

- name: rustup stable
  shell: rustup install stable
  become: yes
  become_user: "{{ user.name }}"

- name: rustup nightly
  shell: rustup install nightly
  become: yes
  become_user: "{{ user.name }}"

- name: rustup update
  shell: rustup update
  become: yes
  become_user: "{{ user.name }}"

- name: rustup default
  shell: rustup default stable
  become: yes
  become_user: "{{ user.name }}"

- name: rustup
  shell: rustup component add "{{ item }}"
  with_items: "{{ pm.rustup }}"
  become: yes
  become_user: "{{ user.name }}"

- name: cargo
  shell: cargo install -f "{{ item }}"
  with_items: "{{ pm.cargo }}"
  become: yes
  become_user: "{{ user.name }}"

- name : cargo nightly
  shell: rustup run nightly cargo install -f "{{ item }}"
  with_items: "{{ pm.cargo_nightly }}"
  become: yes
  become_user: "{{ user.name }}"

- name: npm
  shell: npm install -g "{{ item }}"
  with_items: "{{ pm.npm }}"
