---
- name: Up{dat,grad}e pacman packages
  pacman: update_cache=yes upgrade=yes

- name: Install pacman packages env
  pacman: name={{ pacman.packages.env }} state=present
- name: Install pacman packages db
  pacman: name={{ pacman.packages.db }} state=present
- name: Install pacman packages ime
  pacman: name={{ pacman.packages.ime }} state=present
- name: Install pacman packages lang
  pacman: name={{ pacman.packages.lang }} state=present
- name: Install pacman packages gui
  pacman: name={{ pacman.packages.gui }} state=present
