---
- name: pacman upgrade
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: pacman present
  pacman:
    state: present
    name: "{{ pacman.present }}"
  become: yes

- name: pacman absent
  pacman:
    state: absent
    name: "{{ pacman.absent }}"
  become: yes

- name: aur git
  shell: env LANG=C yay -Y --gendb
  register: gendb
  changed_when: '"No packages were installed" not in gendb.stdout'

- name: aur upgrade
  aur:
    use: yay
    upgrade: yes
    aur_only: yes

- name: aur latest
  aur:
    use: yay
    state: latest
    name: "{{ aur.present }}"
