---
- hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: Set sudo timeout in progress
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^\s*#?\s*Defaults\s+timestamp_timeout\s*=.*'
        insertafter: EOF
        line: 'Defaults timestamp_timeout = 240'
        validate: '/usr/sbin/visudo -cf %s'
      become: yes
      changed_when: False
  roles:
    - ansible-aur
    - user
    - pac
    - dotfiles
    - grub
    - nobeep
    - ssd
    - lidswitch
    - docker
    - virtualbox
    - rust
    - udev
    - vim
    - barrier
  post_tasks:
    - name: Set sudo timeout in progress
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^\s*#?\s*Defaults\s+timestamp_timeout\s*=.*'
        insertafter: EOF
        line: 'Defaults timestamp_timeout = 15'
        validate: '/usr/sbin/visudo -cf %s'
      become: yes
      changed_when: False
