---
- name: Scraping flashplayer dl link
  shell: curl -L https://www.adobe.com/support/flashplayer/debug_downloads.html| sed -n 's/^.*href="\(http.*flash.*player.*sa_linux.x86_64.tar.gz\)".*$/\1/p'
  register: dllink
  args:
    warn: False

- name: Download bin
  shell: cd `mktemp -d` && curl {{ dllink.stdout }}| tar xzvf - && mv flashplayer /usr/local/bin
