---
- name: Install docker
  pacman: name={{ item }} state=present
  with_items:
    - docker
    - docker-compose

- name: Join docker
  shell: usermod -aG docker {{ user.name }}

- name: Enable and start docker
  systemd: name=docker enabled=yes state=started daemon_reload=yes
  become: yes
- name: Pull images
  shell: docker pull {{ item }}
  with_items: "{{ docker.images }}"
