---
- name: Install docker
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Join docker
  shell: usermod -aG docker {{ item }}
  with_items: "{{ docker.group }}"

- name: Enable and start docker
  systemd: name=docker enabled=yes state=started daemon_reload=yes
  become: yes
- name: Pull images
  shell: docker pull {{ item }}
  with_items: "{{ docker.images }}"
