---
- name: HandleLidSwitch in /etc/systemd/logind.conf
  lineinfile:
    dest: /etc/systemd/logind.conf
    state: present
    regexp: '^\s*#?\s*HandleLidSwitch\s*=.*'
    insertafter: '[Login]'
    line: 'HandleLidSwitch = ignore'
  become: yes

- name: HandleLidSwitchDocked in /etc/systemd/logind.conf
  lineinfile:
    dest: /etc/systemd/logind.conf
    state: present
    regexp: '^\s*#?\s*HandleLidSwitchDocked\s*=.*'
    insertafter: '[Login]'
    line: 'HandleLidSwitchDocked = ignore'
  become: yes
